import React from 'react';
import Link from 'next/link';
import { Navbar } from '@/components/Navbar';
import { FinalScreen } from '@/components/FinalScreen';
import { ArrowLeft, FileText, AlertTriangle } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — Mikana',
  description: 'Mikana Terms of Service and User Agreement.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAFAF8] text-[#1C1C1E] flex flex-col font-sans">
      <Navbar />

      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        
        {/* Back Link */}
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#1E56A0] hover:text-[#0B2545] transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Home</span>
          </Link>
        </div>

        {/* Document Header */}
        <div className="border-b border-[#E5E5E0] pb-8 mb-8 space-y-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#EBF2FA] text-[#1E56A0] text-xs font-semibold">
            <FileText className="w-3.5 h-3.5" />
            <span>Official Terms</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-bold tracking-tight text-[#1C1C1E]">
            Terms of Service
          </h1>
          <div className="flex flex-wrap items-center gap-3 text-xs text-[#71717A]">
            <span>Last Updated: September 12, 2026</span>
            <span>•</span>
            <span>Effective Date: September 12, 2026</span>
          </div>
        </div>

        {/* Terms Content */}
        <div className="prose prose-zinc max-w-none space-y-8 text-[15px] leading-relaxed text-[#4A4A48]">
          
          <div className="p-5 rounded-2xl bg-[#EBF2FA]/60 border border-[#D0E2F5] text-[#0B2545] text-sm font-medium">
            Please read these Terms of Service (“Terms”) carefully before using the Mikana mobile application, services, or website (collectively, the “Service”). By creating an account, connecting a WhatsApp session, or subscribing, you agree to be bound by these Terms.
          </div>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">1. Description of the Service</h2>
            <p>
              Mikana is a commercial opportunity discovery and quotation assistant designed for small-to-medium enterprises (SMEs), product merchants, contractors, and service providers. The Service connects with your authorized WhatsApp account to monitor selected commercial groups, classify prospective buyer inquiries using artificial intelligence, match inquiries against your registered business catalog, and assist you in drafting and dispatching fast quotation responses.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">2. AI-Generated Content & Merchant Responsibility</h2>
            <div className="p-4 rounded-xl bg-[#FEF3C7]/60 border border-[#FDE68A] text-[#92400E] flex items-start gap-3 text-sm">
              <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
              <div>
                <strong>Important AI Disclaimer:</strong> Pitch suggestions, message summaries, match scores, and quotation drafts provided by Mikana are generated by automated artificial intelligence models (Google Gemini).
              </div>
            </div>
            <p>As a merchant or contractor, you acknowledge and agree that:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>You retain sole responsibility for reviewing, editing, verifying, and approving any price quotes, delivery timelines, product specifications, or service scopes before sending them to buyers.</li>
              <li>Mikana does not guarantee the financial solvency, intent, identity, or credibility of any prospective buyer detected in group channels.</li>
              <li>You are solely responsible for all sales contracts, order fulfillment, warranty obligations, delivery arrangements, and local tax compliance resulting from your business interactions.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">3. WhatsApp Connection & Platform Compliance</h2>
            <p>To provide lead detection and response capabilities, the Service establishes a multi-device connection to your WhatsApp account upon scanning an authorized QR code. You agree that:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>You will only connect phone numbers and WhatsApp accounts that you own or have explicit legal authority to use for commercial communications.</li>
              <li>You will strictly comply with WhatsApp's Terms of Service, Acceptable Use Policies, and anti-spam regulations.</li>
              <li>You will not use the Service to broadcast unsolicited bulk messages, spam, fraudulent schemes, or prohibited products/services.</li>
              <li><strong>Independence Disclosure:</strong> Mikana is an independent software tool developed by Lui Tech. Mikana is not affiliated with, endorsed by, sponsored by, or officially connected with Meta Platforms, Inc. or WhatsApp LLC.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">4. Subscriptions, Payments & Billing</h2>
            <p>Certain advanced features (such as 24/7 Autopilot dispatching, priority semantic scoring, and unlimited group monitoring) require an active paid subscription:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>In-App Purchases via Google Play:</strong> Subscriptions (e.g., Pro Monthly, Pro Annual, Agency) are purchased through and processed by Google Play In-App Billing.</li>
              <li><strong>Automatic Renewal:</strong> Paid subscriptions automatically renew at the end of each billing cycle unless cancelled at least 24 hours prior to the renewal date via your Google Play account settings.</li>
              <li><strong>Cancellations & Refunds:</strong> You may cancel your subscription at any time through the Google Play Store under <em>Subscriptions</em>. Cancellation takes effect at the end of your current paid billing period. Refund requests are subject to Google Play's standard refund policies.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">5. Prohibited Activities</h2>
            <p>You agree not to use the Service for any unlawful or abusive purpose, including but not limited to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Offering or advertising illegal narcotics, prescription drugs, firearms, stolen property, or counterfeit goods.</li>
              <li>Engaging in deceptive price gouging, phishing, impersonation, or advance-fee fraud.</li>
              <li>Attempting to decompile, reverse-engineer, disrupt, or overload our relay servers or API infrastructure.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">6. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at our discretion, without prior notice, if you violate these Terms, engage in abusive messaging practices, or compromise platform integrity. You may terminate your account at any time by executing the in-app "Delete Account & Data" function or via our web portal.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">7. Disclaimer of Warranties & Limitation of Liability</h2>
            <p>
              The Service is provided on an “AS IS” and “AS AVAILABLE” basis without warranties of any kind, whether express or implied. To the maximum extent permitted by applicable law, Lui Tech and Mikana shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of business profits, customer disputes, data loss, or WhatsApp account restrictions arising from your use of the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-bold text-[#1C1C1E]">8. Governing Law & Contact</h2>
            <p>These Terms shall be governed by and construed in accordance with applicable commercial laws. For inquiries regarding these Terms, please contact:</p>
            <div className="p-4 rounded-xl bg-white border border-[#E5E5E0] space-y-1 text-sm">
              <div className="font-bold text-[#1C1C1E]">Mikana Legal & Support (Lui Tech)</div>
              <div>Email: <a href="mailto:info@lui.co.zw" className="text-[#1E56A0] hover:underline">info@lui.co.zw</a> / <a href="mailto:luitechzw@gmail.com" className="text-[#1E56A0] hover:underline">luitechzw@gmail.com</a></div>
              <div>Phone / WhatsApp: <a href="tel:+263776432893" className="text-[#1E56A0] hover:underline">+263 776 432 893</a> / <a href="tel:+263780331740" className="text-[#1E56A0] hover:underline">+263 780 331 740</a></div>
            </div>
          </section>

        </div>

        {/* Bottom Legal Navigation */}
        <div className="mt-12 pt-8 border-t border-[#E5E5E0] flex flex-wrap items-center gap-6 text-xs text-[#71717A]">
          <Link href="/privacy" className="hover:text-[#1C1C1E] transition-colors underline">
            Privacy Policy
          </Link>
          <Link href="/delete-account" className="hover:text-[#1C1C1E] transition-colors underline">
            Delete Account
          </Link>
          <Link href="/" className="hover:text-[#1C1C1E] transition-colors">
            Mikana Home
          </Link>
        </div>

      </main>

      <FinalScreen />
    </div>
  );
}
